### ISSUE TITLE
Enhance creep death post-effects

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#107]
When a creep dies, they leave a pool of blood on the ground and they fade gradually. Instead, we should use death animation last frame as a corpse and fade it gradually 10 sec. The pool of blood should appear with the same time span under the corpse. Pools of blood should fade by 50% after the wave is finished (so they only stay for 2 waves max).

**Comment by Kvel2D** [comment]
Implemented separate CreepCorpse and CreepBloodPool.
Made corpse fade after 10s, pool still fades after 60s, need to adjust that.

Screenshots from original game:
![2023-09-23 15_13_33-Warcraft III](https://github.com/Praytic/youtd2/assets/13269470/b76870d4-ba8b-4757-beeb-1dba1ae4a93b)
![2023-09-23 15_13_46-Warcraft III](https://github.com/Praytic/youtd2/assets/13269470/1500afb8-8fe9-415b-905d-f64d8f576291)
![2023-09-23 15_14_09-Warcraft III](https://github.com/Praytic/youtd2/assets/13269470/25fd3633-3063-45f0-9a1c-338a87ecb4a0)

**Comment by Kvel2D** [comment]
![gameold](https://github.com/Praytic/youtd2/assets/13269470/6d135939-ffd4-444f-9a8b-be57bd0a8f19)
Implemented death animation for creep corpse but some sprites do not match with their run sprites. Need to reposition them. Champion and boss for example look alright while there is a noticeable "jump" for normal creeps.

**Comment by Kvel2D** [comment]
Nevermind, death animation was drawing at incorrect position because I forgot to apply the "packed offset".

Fixed version:
![gameold](https://github.com/Praytic/youtd2/assets/13269470/709dab92-b2c9-47ed-b47c-014d44875083)

**Comment by Kvel2D** [comment]
Basic version is complete. Can add other visual improvements later.
