### ISSUE TITLE
Enhance Tower Menu user experience

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#143]
- [x] Adapt it for creeps
- [x] Make tower stats window scrollable (how to do it like in bottom bar?)
- [x] Resolve issue with rich text labels not being scalable
- [x] Connect tower icon, tower description and specials to the selected tower
- [x] Make tooltips when hovered over items
- [x] Health, mana and other creep stuff can go into this panel as well

**Comment by Kvel2D** [comment]
Implemented specials and abilities sections the same way as in button tooltip - as text.
If we want to separate them into sections for each special and ability, then create a follow-up issue after this one.

**Comment by Kvel2D** [comment]
Need to allow adding items by dropping them onto inventory UI.
Currently doesn't work, need to drop on tower sprite.

**Comment by Kvel2D** [comment]
> Make tower stats window scrollable (how to do it like in bottom bar?)

This part doesn't work for me.

**Comment by Kvel2D** [comment]
Scrolling of tower info was fixed by 600cfe0f71ae544858b906b7ec3ff741b20398f9
