### ISSUE TITLE
Add a warning when transforming a tower

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#161]
Transform is a mechanic in random game modes where player can build a tower on top of another tower.
Add a popup dialog which has "yes/no" buttons to make sure that player wants to perform the action.

**Comment by Praytic** [comment]
I don't think we need such a precaution. This popup dialog will add more annoyance than a user-friendliness. Towers are replaced very often in Upgrade and Random modes and on higher difficulties it has to be fast.

**Comment by Kvel2D** [comment]
Ok, this was requested by someone in discord.
Could skip the confirmation by default and add a setting to toggle confirming off and on.
Though it's better to have as little settings as possible.

**Comment by Kvel2D** [comment]
Closing for now. Will reopen if more people request and it's judged that this feature is needed.
