### ISSUE TITLE
Implement correct projectile speed and hitscan attacks

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#179]
Some towers like [Rotted Flashing Grave v1](https://interactive.youtd.best/discuss/?id=t650) have hitscan type of attacks with animation. Other towers have different speed of projectiles, so we need to take it into account.

**Comment by Kvel2D** [comment]
Note that Rotted flashing grave plays the laser animation but the damage is applied after a delay. It  seems like the delay between start of animation and application of damage becomes smaller if creep is closer to tower.

**Comment by Kvel2D** [comment]
Moved to Backlog https://github.com/Praytic/youtd2/discussions/407

**Comment by Kvel2D** [comment]
Never mind, reopening because moving this stuff to discussions is a bad idea.

**Comment by Kvel2D** [comment]
Defined projectile speeds for towers.

Task of creating visuals for "hitscan" or long projectiles was added to backlog #407
