### ISSUE TITLE
Come up with new titles and descriptions for all items

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#189]
Items now are grouped into "families" by the same effect they provide to the carrier. The idea is to remake titles and descriptions for items which now have inconsistent icon. Icons were AI-generated so 90% of them don't much the description. Families of items should have somehow related icons and titles. You can find families and items properties here: https://github.com/Praytic/youtd2/tree/main/Data. To get item icons please ask @Praytic to get access to the source file.

**Comment by Kvel2D** [comment]
Started working on this in this google sheet:
https://docs.google.com/spreadsheets/d/1GzsSddZCpvstKTwQKm7hLkG3Sp_-FaKfIeu030uXVos/edit?usp=sharing
