### ISSUE TITLE
Tooltip for upgrade button gets stuck

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#214]
Since #211 

Reproduce:
1. Build a tower
2. Upgrade it
3. Move mouse away from upgrade button

Expected result: tooltip goes away
Actual result: tooltip doesn't go away

![2023-09-19 17_47_05-CompatWindow](https://github.com/Praytic/youtd2/assets/13269470/dc937e1d-15b4-48fd-b2be-764d33b4b9b3)

**Comment by Praytic** [comment]
Fixed
