### ISSUE TITLE
Progress indicator for element buttons is too big

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#217]
![2023-09-20 06_54_00-CompatWindow](https://github.com/Praytic/youtd2/assets/13269470/8321a4d6-91f1-4291-8460-5df4435b7156)

Supposed to look like this:
![2023-09-20 06_54_37-CompatWindow](https://github.com/Praytic/youtd2/assets/13269470/5860fa6e-b422-479b-adf2-864256c8c733)

Reproduce conditions:

- latest HEAD
- latest assets
- no override.cfg (removed it completely from project folder)
- 1080p monitor

**Comment by Praytic** [comment]
Should be fixed on any (conventional) size of monitors.
