### ISSUE TITLE
Tower inventory displays empty slots incorrectly

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#221]
![2023-09-20 17_06_51-CompatWindow](https://github.com/Praytic/youtd2/assets/13269470/88811568-e2bb-48cf-97ed-566f9f0b9ade)

**Comment by Praytic** [comment]
Fixed
![image](https://github.com/Praytic/youtd2/assets/10060411/1131d5ae-d2f0-42fe-84f8-e5e05a1fc34e)
