### ISSUE TITLE
Transmute button is not obvious

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#222]
It looks like a plain image, not like a clickable button which does something.
![2023-09-20 17_08_30-CompatWindow](https://github.com/Praytic/youtd2/assets/13269470/7551ca17-2a19-4966-a83d-053dffd1f3c7)

**Comment by Praytic** [comment]
It is highlighted when the recipe is correct. Do you want me to do it as a text button?

**Comment by Kvel2D** [comment]
Both text button and icon button is okay but it needs to look like a button. It needs borders, change visual state on mouse over and mouse click.

**Comment by Praytic** [comment]
![image](https://github.com/Praytic/youtd2/assets/10060411/4812ba3e-e454-4a75-a584-28579e2b0769)
Now it looks more like a button
