### ISSUE TITLE
Items are displayed incorrectly in horadric cube

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#223]
![2023-09-20 17_08_02-CompatWindow](https://github.com/Praytic/youtd2/assets/13269470/90b9118f-bb4f-42a1-a844-b0871bd38300)

**Comment by Praytic** [comment]
Fixed
![image](https://github.com/Praytic/youtd2/assets/10060411/c5b899d1-41a5-4973-a362-5557179a94d6)
