### ISSUE TITLE
Display creep specials in the unit menu

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#239]
Same as for towers.

Creep specials are displayed as buffs but it is inconvenient to check them this way. Would be more convenient to be able to see the description of all specials which the creep has in the unit menu.

Note: "unit menu" is "tower menu". TowerMenu currently performs double duty of displaying info for both selected towers and selected creeps.

**Comment by Praytic** [comment]
TowerMenu has been renamed to UnitMenu.
