### ISSUE TITLE
Add "Most kills" to game stats

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#240]
Most kills (total)
and
Most kills (last minute)

Useful to know which towers will benefit the most from bounty and experience bonuses.

**Comment by Praytic** [comment]
`Most kills (last minute)` is not useful because in 95% of game time it will be the same carry tower as in `Most kills (total)`. It may differ only at the beginning or when a boss kill is stolen by some other tower and it has 1 kill as the biggest one since the last minute.

**Comment by Kvel2D** [comment]
Ended up adding only "Most kills".
