### ISSUE TITLE
Clicking off the element should deselect the element towers and show all towers. 

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#252]
Reason being, it is not clear at first you need to click on each element to get the towers for the element.

**Comment by Kvel2D** [comment]
Correction: not "clicking off the element" but "clicking on element while it's already selected".
So that it behaves like a toggle.
Check item stash filter buttons because they work this way currently.

**Comment by Kvel2D** [comment]
Closing this because this logic doesn't fit in current UI flow.
