### ISSUE TITLE
Rework auras inclusion algorithm to match WC3

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#279]
![image](https://github.com/Praytic/youtd2/assets/10060411/74b158ad-2391-4c0b-a7da-12cd2f6f7c09)
This image shows how auras work in You TD 2. Compared to WC3 version, this is a different behavior. In WC3 map towers were affected by the aura if the aura range overlaps with the tower building area.

**Comment by Kvel2D** [comment]
Demonstration with Skink tower which has 200 aura range.
Note that in WC3 distance between center of "tiles" is 128.
![2023-11-17 06_50_28-Warcraft III](https://github.com/Praytic/youtd2/assets/13269470/6e5d18f5-efa8-4975-958e-52180f64bda4)
![2023-11-17 06_50_06-Warcraft III](https://github.com/Praytic/youtd2/assets/13269470/b5559979-fcee-415b-846b-0e9cd17797a7)

**Comment by Kvel2D** [comment]
Investigated auras which target creeps.

The conclusion is that they *do not* extend rand by 64 like towers.

Tested using Icy Core tower which has an aura with range of 800 which applies a slow debuff to creeps.

In range @ 768
![in range](https://github.com/Praytic/youtd2/assets/13269470/6f774478-409c-4438-b1d2-96a7fb3c665b)

Out of range @ 832
![out of range](https://github.com/Praytic/youtd2/assets/13269470/37fba0ce-c622-4379-bd57-b3d808f15243)

**Comment by Kvel2D** [comment]
This +64 extension appears to also apply to tower abilities which affect towers in range.
For example, fiery dog has ability with range of 420 but it affects this tower at 461 distance.
![2023-11-17 18_02_37-Warcraft III](https://github.com/Praytic/youtd2/assets/13269470/0484495d-28ea-410a-a26d-2fcdb6a1a9af)
