### ISSUE TITLE
Improve the indication of which towers are affected by the selected or currently-being-built tower.

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#280]
As a suggestion: selected or currently-being-built tower aura can highlight grid cells which are overlapping with it. Towers on these cells can be highlighted as well with periodic pulsing modulate color.

**Comment by Kvel2D** [comment]
Moved to Backlog https://github.com/Praytic/youtd2/discussions/407

**Comment by Kvel2D** [comment]
Never mind, reopening because moving this stuff to discussions is a bad idea.

**Comment by Kvel2D** [comment]
There were some problems with aura ranges and they should be fully fixed now. Visual aura range should now match with affected towers much better than before.
