### ISSUE TITLE
Make mana bars smaller and click-through

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#306]
![image](https://github.com/Praytic/youtd2/assets/10060411/dda13eef-4a92-418a-a307-88620a5863fb)

**Comment by Kvel2D** [comment]
Closed by fc2683b4b0e4671a608f38d55484d21671a233b2 and ba6c0d9be2f823cf9cbad1bf4bb0916d8358fecf

New size:
![2023-11-26 07_45_17-YouTD 2 (DEBUG)](https://github.com/Praytic/youtd2/assets/13269470/4ee868dd-dc74-4820-b9a1-7d7f7ef2a86b)
