### ISSUE TITLE
Boss sprite shouldn't have such a reduced quality

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#316]
![image](https://github.com/Praytic/youtd2/assets/10060411/04a8585e-3254-4d63-8890-b4d8dbd2fe93)

**Comment by Kvel2D** [comment]
Moved to Backlog https://github.com/Praytic/youtd2/discussions/407

**Comment by Kvel2D** [comment]
Never mind, reopening because moving this stuff to discussions is a bad idea.

**Comment by Kvel2D** [comment]
![2024-07-06 22_07_15-YouTD 2 (DEBUG)](https://github.com/Praytic/youtd2/assets/13269470/54d77401-9a42-428f-9987-0c2602bf1912)

Switched from x0.7 Lossy to Basis Universal compression mode. The amount of artifacts is reduced, looks decent now.
