### ISSUE TITLE
ButtonTooltip is not hidden when ItemButton is scrolled outside of visible area

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#330]
<img width="803" alt="Screenshot 2023-12-16 at 2 03 41 PM" src="https://github.com/Praytic/youtd2/assets/10060411/47e17ccd-6a36-42bc-aa6d-169d4495fcb1">

**Comment by Kvel2D** [comment]
Couldn't find a solution to this. The tooltip goes away when you move the mouse so it's not critical.
