### ISSUE TITLE
Game crashed due to Vulkan error

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#339]
Last entries in logs which might caused the crash:
```
...
Creep has been spawned [Creep:<Node2D#122329124318092>].
Project FPS: 75 (13.33 mspf)
Creep has been spawned [Creep2:<Node2D#122378700991976>].
Vulkan queue submit: Swapchain is out of date, recreating.
Vulkan: Early out of date swapchain, recreating.
```

This is supposedly related issue: https://github.com/godotengine/godot/issues/74963

**Comment by Kvel2D** [comment]
Related issue is closed and I didn't manage to reproduce this in newer versions. Closing.
