### ISSUE TITLE
Solve duplication of SelectionMaterial code per Unit instance

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#344]
Due to `canvas_item` not having `instance uniform` variables, we have to make material "local to scene". This causes the code to embed into the scene. Issue should be resolved when https://github.com/godotengine/godot/issues/62943 is resolved and project version is upgraded.

**Comment by eliacanavera1111** [comment]
I have many Sprite2D inside my subviewport, all with the same shader, that has a parameter for on/off.
But if I activate or deactivate one of them, they all change their state. I can't find how to make them per-instance.
> Due to `canvas_item` not having `instance uniform` variables, we have to make material "local to scene".

I tried making each of my sprites local with "sprite2d.material.resource_local_to_scene = true", but it's not working:
```
func add_shader_to_sprites():
    var myshader:= ShaderMaterial.new()
    myshader.shader = load("res://newshader.gdshader")
        for sprite2d in arrayofsprites:
            sprite2d.material = myshader
            sprite2d.material.resource_local_to_scene = true
```
```
func sprite_pressed():
    # to activate the shader only on this sprite
    sprite2d.get_material().set_shader_parameter("onoff", 1) 
```
