### ISSUE TITLE
Can't start moving items while building a tower.

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#348]
Reproduce:
1. Open tower stash.
2. Start building a tower.
3. Open item stash.
4. Try moving an item.

Tower preview is drawn behind the menu so it looks like the game is bugged because player is clicking on an item and nothing happens and player can't see that he is currently building a tower.

**Comment by Praytic** [comment]
Fixed. Currently when you try to interact with items inside the ItemStashMenu while holding a TowerPreview nothing happens. You'll need to release the TowerPreview in order to interact with items.
