### ISSUE TITLE
Create icons for tower effects and spells

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#379]
- [x] AbandonedPit1.gd
- [x] AbominableSnowman1.gd
- [ ] AfflictedObelisk1.gd
- [ ] AncientEnergyConverter1.gd
- [ ] AnnoyedTree1.gd
- [ ] ArcaneStorm1.gd
- [ ] AreaRoaster1.gd
- [ ] AshGeyser1.gd
- [x] AstralLantern1.gd
- [ ] AstralRift1.gd
- [x] BabyPlant1.gd
- [ ] BabyTuskar1.gd
- [ ] BallLightningAccelerator1.gd
- [ ] BasicKnowledge1.gd
- [ ] BlackDragonRoost1.gd
- [ ] Blackrock'sTotem1.gd
- [ ] BombTurret1.gd
- [ ] BoneShrine1.gd
- [ ] Bonk,theLivingMountain1.gd
- [ ] BrokenCage1.gd
- [x] BrokenCircleofWind1.gd
- [ ] BrokenFirePit1.gd
- [ ] BrokenLightningRod1.gd
- [ ] BronzeDragonRoost1.gd
- [ ] BuriedSoul1.gd
- [x] BurningWatchtower1.gd
- [ ] Burrow1.gd
- [ ] CagedFire1.gd
- [ ] Cenarius1.gd
- [ ] ChainingStorm1.gd
- [ ] ChargedObelisk1.gd
- [ ] ChilledSpire1.gd
- [ ] CloudWarrior1.gd
- [ ] CloudyTempleofAbsorption1.gd
- [ ] CoconutSapling1.gd
- [ ] CoinMachine1.gd
- [ ] ColdObelisk1.gd
- [ ] ColdTroll1.gd
- [ ] CrimsonWyrm1.gd
- [ ] CruelFire1.gd
- [ ] CursedGrounds1.gd
- [ ] CuteSmallSpider1.gd
- [ ] DarkBattery1.gd
- [x] DarkFirePit1.gd
- [ ] DeathKnight1.gd
- [ ] DimensionalFluxCollector1.gd
- [ ] DragonSorcerer1.gd
- [ ] DrakeWhisperer1.gd
- [ ] Dreadlord1.gd
- [ ] Dutchman'sGrave1.gd
- [x] DwarvenForgery1.gd
- [ ] EbonfrostCrystal1.gd
- [ ] EmbershellTurtleHatchling1.gd
- [ ] EnergyJunction1.gd
- [ ] EredarWarlock1.gd
- [ ] EssenceofFury1.gd
- [x] Felweed1.gd
- [x] FieryDog1.gd
- [x] FieryPebble1.gd
- [ ] FireBattery1.gd
- [ ] FireStar1.gd
- [ ] FirestormCell1.gd
- [ ] Fisherman1.gd
- [x] ForestArcher1.gd
- [ ] ForestProtectress1.gd
- [x] FrostRoot1.gd
- [ ] FrostyRock1.gd
- [ ] FrozenWell1.gd
- [ ] Furbolg1.gd
- [ ] GardenofEden1.gd
- [ ] GatlingGun1.gd
- [ ] GenisSage1.gd
- [ ] GeothermalExtractor1.gd
- [ ] GlaiveMaster1.gd
- [x] GlowingSolarOrb1.gd
- [ ] GnollThunderMage1.gd
- [ ] GoblinStronghold1.gd
- [ ] Grab-o-Bot1.gd
- [ ] GreenDragonRoost1.gd
- [ ] GreenLightning1.gd
- [ ] GryphonRider1.gd
- [ ] HallofSouls1.gd
- [ ] Harby1.gd
- [ ] HarpyWitch1.gd
- [x] HauntedRubble1.gd
- [ ] HealingObelisk1.gd
- [ ] HellBat1.gd
- [ ] HolyEnergy1.gd
- [ ] IceBattery1.gd
- [ ] IcyCore1.gd
- [x] IcySkulls1.gd
- [ ] IcySpirit1.gd
- [ ] Igloo1.gd
- [ ] InexperiencedHuntress1.gd
- [ ] InflamedStone1.gd
- [ ] InitiateElementalist1.gd
- [ ] It1.gd
- [ ] JungleStalker1.gd
- [x] LesserAstralDefender1.gd
- [x] LesserDarkDefender1.gd
- [ ] LesserElementalGhost1.gd
- [x] LesserFlamyDefender1.gd
- [x] LesserIceDefender1.gd
- [x] LesserIronDefender1.gd
- [x] LesserNaturalDefender1.gd
- [ ] LesserPriest1.gd
- [ ] LesserSkeletalMage1.gd
- [x] LesserStormDefender1.gd
- [ ] LesserWolvesDen1.gd
- [ ] LibraryofAlexandria1.gd
- [ ] LichKing1.gd
- [ ] LightningEye1.gd
- [ ] LightningGenerator1.gd
- [ ] LightningTotem1.gd
- [ ] LittlePhoenix1.gd
- [ ] LivingVolcano1.gd
- [ ] LunarEmitter1.gd
- [x] LunarSentinel1.gd
- [ ] MagicBattery1.gd
- [ ] MagicMushroom1.gd
- [ ] MagnataurWarrior1.gd
- [ ] Mana-TouchedDrake1.gd
- [ ] Marine1.gd
- [ ] MeteorTotem1.gd
- [ ] MilitiaWatchtower1.gd
- [ ] Miner1.gd
- [x] MinorMagicRuin1.gd
- [ ] MonolithofChaos1.gd
- [ ] Morphling1.gd
- [x] MossyAcidSprayer1.gd
- [ ] MudGolem1.gd
- [ ] NatureSprites1.gd
- [ ] NecromanticAltar1.gd
- [ ] NerubianQueen1.gd
- [ ] new_shader.gdshader
- [ ] NortromtheSilencer1.gd
- [ ] NuclearMissileLauncher1.gd
- [x] ObeliskofFortuity1.gd
- [ ] OwlofWisdom1.gd
- [ ] ParticleAccelerator1.gd
- [ ] Phantom1.gd
- [ ] PlaguedCrypt1.gd
- [ ] PlanarGate1.gd
- [ ] PoisonBattery1.gd
- [ ] PolarBearCub1.gd
- [ ] PrinceofLightning1.gd
- [ ] PrincessofLight1.gd
- [ ] QuillboarThornweaver1.gd
- [ ] RedBallLightning1.gd
- [ ] RegeneratingWell1.gd
- [x] RootedChasm1.gd
- [ ] RottedFlashingGrave1.gd
- [ ] RowingBoat1.gd
- [x] RuinedMonolith1.gd
- [x] RuinedStormCap1.gd
- [x] RuinedSunPedestal1.gd
- [ ] RuinedWindTower1.gd
- [ ] RundownIronSentry1.gd
- [ ] SacredAltar1.gd
- [ ] SacrificialLamb1.gd
- [ ] Sapphiron'sColdGrave1.gd
- [ ] Scales1.gd
- [ ] SeaTurtle1.gd
- [ ] ServantoftheTwinFlames1.gd
- [ ] SewerConnection1.gd
- [ ] Shadow1.gd
- [ ] Shaman1.gd
- [ ] ShardofSouls1.gd
- [ ] SilverKnight1.gd
- [ ] Skink1.gd
- [ ] SmallBrazier1.gd
- [ ] SmallBugNest1.gd
- [x] SmallCactus1.gd
- [x] SmallFireSprayer1.gd
- [ ] SmallFrostFire1.gd
- [ ] SmallFrozenMushroom1.gd
- [ ] SmallIceMine1.gd
- [x] SmallLight1.gd
- [x] SmallPocketRocket1.gd
- [ ] SmallRayBlaster1.gd
- [ ] SmallSerpentWard1.gd
- [ ] SmallTorch1.gd
- [ ] Sniper1.gd
- [x] SnowyPebble1.gd
- [ ] SolarCollector1.gd
- [ ] SolarEmitter1.gd
- [ ] Sorceress1.gd
- [ ] SoulflameDevice1.gd
- [ ] SoulVault1.gd
- [ ] SpellCollector1.gd
- [ ] StarGazer1.gd
- [ ] StormBattery1.gd
- [ ] StormCoil1.gd
- [ ] StormFocus1.gd
- [ ] StormyDog1.gd
- [ ] SunCrusader1.gd
- [ ] Taita,TheHermit1.gd
- [ ] Teacher1.gd
- [x] TentacleSpawn1.gd
- [ ] TheConduit1.gd
- [ ] TheCouncilofDemons1.gd
- [ ] TheFireLord1.gd
- [ ] TheFrozenWyrm1.gd
- [ ] TheFurnace1.gd
- [ ] TheOmnislasher1.gd
- [ ] TheSteamEngine1.gd
- [x] ThiefApprentice1.gd
- [ ] TidewaterStream1.gd
- [ ] TimeManipulator1.gd
- [ ] Timevault1.gd
- [x] TinyShrub1.gd
- [ ] TinyStormLantern1.gd
- [x] Tombstone1.gd
- [ ] tower_template.gd
- [x] TrashHeap1.gd
- [x] TreeStump1.gd
- [ ] TundraStalker1.gd
- [ ] UndisturbedCrypt1.gd
- [ ] Valor1.gd
- [ ] VillageWitch1.gd
- [ ] VoidDrake1.gd
- [ ] Vol'jintheWitchDoctor1.gd
- [ ] Vulshok,theBerserker1.gd
- [ ] WarriorofLight1.gd
- [ ] WildKodoBeast1.gd
- [x] WoodenTrap1.gd
- [ ] XenoResearchFacility1.gd
- [ ] Ymir1.gd
- [ ] YoungNorthernTroll1.gd
- [ ] Zealot1.gd
- [ ] Zeus1.gd

**Comment by Praytic** [comment]
Icons were taken from: https://game-icons.net/

**Comment by Kvel2D** [comment]
I am planning to do this by reusing icons from items and towers, with some modifications.
