### ISSUE TITLE
Shortcuts mix key values and positions

### ISSUE THREAD

**Issue by basxto** [Praytic/youtd2#396]
Some shortcuts are bound to the position of keys and others are bound to their value.
This can lead to a double occupation of keys.

On my neo2 keyboard layout I have the keys VUIA where QWERTY/Z has WASD. That means the I key moves the camera down, because this done via key positions.

But the I key also toggles the inventory via key value.

Result of that is that pressing the I key moves the camera down and toggles the inventory at the same time.

**Comment by Kvel2D** [comment]
I've changed all shortcuts to use physical keycodes, so now there won't be overlaps. The downside is that the shortcut displayed in button tooltip is not accurate for non-QWERTY keyboard.
For example, on neo2 keyboard the item stash shortcut will show as "I" in tooltip but you need to press "G" instead.

I think that fixing the visual issue is possible but it's low prio at the moment. Might be done at some point in the future.

Closed by c500e989f26cbbc91cd36bab9defea69d75c3529
