### ISSUE TITLE
Infinite loop detected when trying to build a tower in guided tutorial mode

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#397]
Follow all steps and then you'll have hard crash when you click on a tower icon:
<img width="872" alt="Screenshot 2024-03-04 at 7 19 32 PM" src="https://github.com/Praytic/youtd2/assets/10060411/6bbb0b64-2f0e-49d1-91a5-afb068ac0fa3">

**Comment by Kvel2D** [comment]
Note that I had to choose "Random" build mode and click on a tower button with 1 stack count to reproduce this issue.

**Comment by Kvel2D** [comment]
Closed by 338eed99dd84a7fd98b944d9289637e18bf8860c
