### ISSUE TITLE
Time control

### ISSUE THREAD

**Issue by basxto** [Praytic/youtd2#413]
It would be neat to be able to pause (without the menu) and accelerate time in singleplayer.

Pausing can help slow readers to thoroughly read all the item descriptions the first time they encounter them.

Accelerated time for when mobs leak or when you are sure the towers can handle the wave.

**Comment by Kvel2D** [comment]
I implemented increasing game speed but not pausing.
During playtests I noticed that the timer between waves is useful to discourage too much micro-managing of items in tower inventories. Adding a pause function would remove that and enable extreme micro managing.
