### ISSUE TITLE
Situation where player doesn't roll towers during pre-game is not handled

### ISSUE THREAD

**Issue by phatnguyentan** [Praytic/youtd2#438]
![image](https://github.com/Praytic/youtd2/assets/13960540/e65eed02-4e61-4af7-9f53-b3454ed33f74)

![image](https://github.com/Praytic/youtd2/assets/13960540/2ce2b33d-8d9d-4abe-944a-be6cc5a25b72)

**Comment by Kvel2D** [comment]
There is a 3 minute timer before first wave, you are supposed to research elements and roll towers before that 3 minute timer expires.
The problem is that the game doesn't handle the situation of "player does nothing for 3 minutes" correctly.

**Comment by Kvel2D** [comment]
I made the "roll towers" button stay around if player fails to use it before first wave. Also, there's a warning message which suggests to the player to restart.

**Comment by phatnguyentan** [comment]
I can roll tower and play, but it's make me confusing, should we have default towers instead of roll towers
