### ISSUE TITLE
Score multiplier for Challenge creep sizes are incorrect

### ISSUE THREAD

**Issue by Coder-Li** [Praytic/youtd2#441]
https://github.com/Praytic/youtd2/blob/4cd0b1f4069e055714da3796ee14a70753f1e02f/src/enums/creep_size.gd#L71

Hello, I'm new to godot and I've benefited a lot from the code of this project.
Can I get access to static resources?   :)

**Comment by Kvel2D** [comment]
Hello.
Yes, those values are really incorrect. They are supposed to be as in the comment above. Thanks for reporting this!

**Comment by Coder-Li** [comment]
Yes, that's exactly what I needed! thank
