### ISSUE TITLE
It's not a bug here, but it can be optimized

### ISSUE THREAD

**Issue by Coder-Li** [Praytic/youtd2#442]
https://github.com/Praytic/youtd2/blob/5f8beed8c828240b107bf1b7f661ce1cafc74d3a/src/creeps/wave.gd#L336

look at 383 line
https://github.com/Praytic/youtd2/blob/5f8beed8c828240b107bf1b7f661ce1cafc74d3a/src/creeps/wave.gd#L383

--- 
By the way

I don't really understand creep_size naming that. I think it's kind of like creep_category.
creep_category -> creep_race

(sorry, my English is poor)

**Comment by Coder-Li** [comment]
Another question

https://github.com/Praytic/youtd2/blob/5f8beed8c828240b107bf1b7f661ce1cafc74d3a/src/creeps/wave.gd#L321

Is the value of the c variable correct?
When HARD c = 0.004 but EXTREME c = 0.001

**Comment by Kvel2D** [comment]
I added usage of is_challenge() here: 3ce33ac4318c5ac44ba7004a7ee6b0e2e7e5cd80

And fixed typo in armor formula here: 1be8de527037f2a4f5be14253addaeb97ce6a475
It really was a bug, the value for HARD is supposed to be `0.0004`, not `0.004`.

> I don't really understand creep_size naming that. I think it's kind of like creep_category.
creep_category -> creep_race
Yeah, that terminology ended up in a confusing. Carried over from original game.
- "Creep category" is same thing as "Creep race".
- The concept of "Challenge" exists both in "creep size" and in "creep category".
- "Challenge boss" and "Challenge mass" sizes always have "Challenge" category.
- "Challenge boss" creep cannot be an "orc" category. It has to be "Challenge" category.
- "Air" creep cannot be "Challenge mass" size (also can't be "Challenge boss" size)
