### ISSUE TITLE
Maverick does not reduce wisdom upgrade strength

### ISSUE THREAD

**Issue by PiotrKaszuba** [Praytic/youtd2#447]
Hello, I just found that Maverick does not reduce wisdom upgrade strength (item find at 112% in the beginning).

The problem seems to origin from not using ["player.get_wisdom_upgrade_effect_multiplier()"](https://github.com/Praytic/youtd2/blob/09f42261ecc80e1ef257ad045193f5e044018ee4/src/player/player.gd#L568). This could probably be fixed by getting and applying that modifier in:

https://github.com/Praytic/youtd2/blob/09f42261ecc80e1ef257ad045193f5e044018ee4/src/actions/action_select_wisdom_upgrades.gd#L14 and https://github.com/Praytic/youtd2/blob/09f42261ecc80e1ef257ad045193f5e044018ee4/src/actions/action_select_wisdom_upgrades.gd#L27

or handling it internally in ["player.set_wisdom_modifier"](https://github.com/Praytic/youtd2/blob/09f42261ecc80e1ef257ad045193f5e044018ee4/src/player/player.gd#L572)

Also, in order to handle this correctly this 
https://github.com/Praytic/youtd2/blob/09f42261ecc80e1ef257ad045193f5e044018ee4/src/builders/instances/builder_maverick.gd#L14

should probably be changed to "player.set_wisdom_upgrade_effect_multiplier(player.get_wisdom_upgrade_effect_multiplier() - 0.375)".  It seems that same will apply for Feeble Fender.

I'm not too familiar with the codebase so I might have missed something. 
I'm currently missing testing/debugging setup - if you could point me to some existing dev workflow/build/test guide of this project I could be able to prepare a pull request for it myself.

![image](https://github.com/user-attachments/assets/ef66316f-617d-486f-a865-037bf5579c4e)

**Comment by Kvel2D** [comment]
I checked and managed to reproduce this bug. I will take a look and prepare a fix.

Thank you for reporting this!

**Comment by Kvel2D** [comment]
Screenshots after fix

Feeble Fender:
![2024-09-25 19_51_59-YouTD 2 (DEBUG)](https://github.com/user-attachments/assets/c71d2293-5db7-4785-a9b8-8be757b7cd83)
![2024-09-25 19_52_08-YouTD 2 (DEBUG)](https://github.com/user-attachments/assets/33d5951a-dafb-447a-a593-2dae3cccdcca)
Exp ratio +20% base x 1.25 from feeble fender = +25% = 125% total

Maverick:
![2024-09-25 19_52_28-YouTD 2 (DEBUG)](https://github.com/user-attachments/assets/a6e02593-a5fe-4436-98ea-f5a95b976130)
![2024-09-25 19_54_24-YouTD 2 (DEBUG)](https://github.com/user-attachments/assets/099b23a5-e058-4053-a0b2-1f03d025c4d2)
Exp ratio +20% base x0.625 from maverick = +13% = 113% total
