### ISSUE TITLE
Bonus DPS mod (MOD_DPS_ADD) calculation not consistent with original YouTD

### ISSUE THREAD

**Issue by PiotrKaszuba** [Praytic/youtd2#449]
DPS mod uses current attack speed which is inconsistent with original YouTD that used base attack speed. It is also annoying when playing knowing that your attack speed bonuses 'work against' your damage per hit (after I've discovered that).

https://github.com/Praytic/youtd2/blob/48ce2674c62e3e008b9370aae3e5f920bb23efc0/src/towers/tower.gd#L1113-L1118

Another layer of inconsistency is that resulting bonus damage from DPS * base_attack_speed calculation was added to "damage add" originally so it was affected by "damage add %" bonuses, while here it is not affected.

Here's example of DPS mod and damage add % on a tower: 450 dps add * 1.6 base attack speed = 720 damage add. And +5% from damage add % also applied on top of it which is confirmed by calculating ((1076*0.91) + 720) * 1.05 ~= 1784.
![image](https://github.com/user-attachments/assets/eeeb2c3a-ecff-48a9-a07b-a6d5f2abe2d3)

In order to replicate original functionality that code could look like:
```
        var dps_bonus: float = get_dps_bonus()
        var attack_speed: float =  get_base_attack_speed()
	var dps_mod: float = dps_bonus * attack_speed

	var overall_base_damage: float = (base_damage + base_bonus) * base_bonus_percent
	var overall_damage: float = (overall_base_damage + damage_add + dps_mod) * damage_add_percent
```

I'm not aware of other places in the code that would need to be modified. All this is relevant unless that change is intentional. If it is intentional - it feels sort of wrong for someone who played YouTD for years.

Thanks for your time!

**Comment by Kvel2D** [comment]
This is not intentional, it's a mistake. The goal is to have same combat logic as original YouTD.

> DPS mod uses current attack speed which is inconsistent with original YouTD that used base attack speed.

Confirmed, check JASS code from original game below.
```lua
function Xcv takes integer D0,integer P6,real k5 returns nothing

...

if(P6==5)then
// k5 is value of MOD_DPS_ADD
// dC[cL[D0]] is base attack cooldown
set P6=3
set k5=k5*dC[cL[D0]]
endif
```

> Another layer of inconsistency is that resulting bonus damage from DPS * base_attack_speed calculation was added to "damage add" originally so it was affected by "damage add %" bonuses, while here it is not affected.

Confirmed.

```lua
MOD_DPS_ADD

...

// km = base damage and MOD_DAMAGE_BASE and MOD_DAMAGE_BASE_PERC
// sL[SL[D0]+3] = MOD_DAMAGE_ADD and "dmg bonus from MOD_DPS_ADD"
// sL[SL[D0]+4] = MOD_DAMAGE_ADD_PERC
set Km=R2I((km+sL[SL[D0]+3])*(1+sL[SL[D0]+4])-km)
call vLv(bL[D0],0,vm[xm[D0]+3],Km)
set vm[xm[D0]+3]=Km
```

**Comment by Kvel2D** [comment]
Frozen Root, max upgrade, Short Sword (+5% damage add), Tooth Trophy (+450DPS), 0.75 attack cooldown
Before fix:
```
1132->1526
1132 * 1.05 + 450 * 0.75 = 1188,6 + 337.5 = 1526
```
![before fix](https://github.com/user-attachments/assets/e0ab361a-2d86-4d83-b05b-902ec9595a7e)

After fix:
```
1132->1543
(1132 + 450 * 0.75) * 1.05 = 1132 + 337.5 = 1543
```
![after fix](https://github.com/user-attachments/assets/809fd6f0-147c-48c0-8b79-991c5ca8cc1b)

**Comment by Kvel2D** [comment]
Closed by 0d3aea604ca775c50d16934b0cffac3c878d7764 and fcfbcf6d6c331d144d8525955bdf2ce594c02d79

**Comment by PiotrKaszuba** [comment]
Thank you for such quick fix!

One more point to look for (idk how current build works): the multiboard for tower could show damage add (flat) coming from DPS increases - as it is the case in original game (the screenshot with Skilled Witch that I provided) and I suspect that it will not be the case given the scope of those updates (I assume it will use only "damage_add" property from tower and not "damage add" + "DPS add * base attack speed").

**Comment by PiotrKaszuba** [comment]
I just thought about it and maybe even this part could be removed from damage calculation:

https://github.com/Praytic/youtd2/blob/b879e2edeea954bfb94a82cf9b4c4fa8ed59482f/src/towers/tower.gd#L1113-L1115

and become a part of this function (it would combine "static" damage add and DPS damage add):

https://github.com/Praytic/youtd2/blob/b879e2edeea954bfb94a82cf9b4c4fa8ed59482f/src/unit/unit.gd#L1771

or a similar function i.e. "get_total_damage_add".

It then could possibly correctly display in the multiboard too I assume.

That's just a suggestion, thanks again for you time!

**Comment by Kvel2D** [comment]
> Thank you for such quick fix!
> 
> One more point to look for (idk how current build works): the multiboard for tower could show damage add (flat) coming from DPS increases aswell - as it is the case in original game (the screenshot with Skilled Witch that I provided) and I suspect that it will not be the case given the scope of those updates (I assume it will use only "damage_add" property from tower and not "damage add" + "DPS add * base attack speed").

Oh yeah, you're right. Original game does display "Damage add" stat as "damage add" + "bonus from MOD_DPS". Will fix that.
