### ISSUE TITLE
Dark matter trident bug

### ISSUE THREAD

**Issue by PiotrKaszuba** [Praytic/youtd2#454]
Dark matter trident item applies incorrect mods (swapped movespeed and attackspeed) between its buffs: boost_bt should use the modification from drain_bt and vice versa:

https://github.com/Praytic/youtd2/blob/af24582e3f0794cfcce2cdc65644140382565622/src/items/item_behaviors/dark_matter_trident.gd#L24-L37

**Comment by Kvel2D** [comment]
Extra fix in 20d0b763614ab62f9c0635f5b32109c2e45bddd8
