### ISSUE TITLE
Left and right camera and tab switching ambiguity

### ISSUE THREAD

**Issue by PiotrKaszuba** [Praytic/youtd2#457]
It seems that WSAD camera control is quite intuitive (for me) - seems to work same as arrows.

However, after clicking (left click) labels of one of the tabs in upper left corner HUD (Wave Status / Game Stats) it seems to get selected after which using left / right A/D switches between tabs until unselected. Similarly, tabs on tower view seem to be selected that way. Moreover, it seems that one can use TAB to switch this selection from upper left HUD to tower HUD and vice-versa. 

The only way I seem to be able to unselect a HUD tab is to switch selection to tower HUD tab and unselect the tower - I'd do this to avoid tab switching while moving the camera actively during gameplay.

All of this is confusing - left/right and/or A/D should only control the camera - the tabs switching are very annoying.

I suggest changing HUD tab switching to only 1 independent hotkey that would work as 'right' for the selected tab.

**Comment by PiotrKaszuba** [comment]
Tested only using Windows application version

**Comment by Kvel2D** [comment]
Was fixed in 1f453fb0184e21b39fed562167f46fc48df99a9b

**Comment by PiotrKaszuba** [comment]
It still seems to happen for tower HUD.
