### ISSUE TITLE
QoL: item cooldowns in stash

### ISSUE THREAD

**Issue by PiotrKaszuba** [Praytic/youtd2#459]
Suggestion to display item cooldowns while in stash and horadric cube as currently they are shown only while held by towers. If player is  planning to maximize usage of item ability while switching to other items - they have to bring the item to tower to check its cooldown and wait a few seconds or have already lost a few seconds of cooldown - which is annoying and inconvenient.

**Comment by PiotrKaszuba** [comment]
This is probably buffing active items though. In original YouTD player probably only saw item cooldowns while in tower.

**Comment by PiotrKaszuba** [comment]
Also item charges could be visible as well.

**Comment by Kvel2D** [comment]
I think showing item cooldowns in item stash would cause visual clutter.

Maybe make default behavior to not show but add ability to enable it with "/show-item-cooldowns-in-stash"?

**Comment by PiotrKaszuba** [comment]
That would work I believe. But maybe whole item stash is indeed too much.

Let's think about applying this only to horadric cube and/or any additional inventories I've suggested in #460 that could mimic hero/builder inventory from original game. Not sure, but I believe cooldowns of items were visible there.

**Comment by Kvel2D** [comment]
Item cooldowns are visible in horadric cube since #462
I consider this closed
