### ISSUE TITLE
Range check for tower attacks is off by 8

### ISSUE THREAD

**Issue by PiotrKaszuba** [Praytic/youtd2#472]
Observations:
- a lot of range checks (one per creep I assume) when creeps out of range - would the same apply for every tower * every creep?

![range_checks2](https://github.com/user-attachments/assets/dbc6b1bf-73cc-49f2-a418-05f543220d9c)

- when in range - checks are much more rare (when attack is ready). I get that it is known and optimized specifically for bonus round when towers almost always have attacks on cooldowns
- however, we get one check with 772 range - most likely missing +8 from RANGE_CHECK_BONUS_FOR_OTHER_UNITS

![Zrzut ekranu 2024-10-11 225219](https://github.com/user-attachments/assets/9491ef25-ccbd-45b8-a93d-e008b7024862)

- same for this boss

![Zrzut ekranu 2024-10-11 225354](https://github.com/user-attachments/assets/2a14d90f-0003-47e1-b2cb-e76dedd9ff20)

- we get some checks that would allow the boss to be attacked (distance 777) range: 780 from code (tower.gd):  
`var creeps_in_range: Array = Utils.get_units_in_range(self, _attack_target_type, get_position_wc3_2d(), attack_range)`
- and other one that does not (distance 772) in tower.gd too:
'var target_is_valid: bool = _target_is_valid(new_target)'

![Zrzut ekranu 2024-10-11 225449](https://github.com/user-attachments/assets/3df881a0-94d2-42c6-9ef6-2b285147388b)

- and then checks get less frequent but still 780 and 772:

![Zrzut ekranu 2024-10-11 225548](https://github.com/user-attachments/assets/a8dd6f0b-9901-49a6-b71a-f0267b5976b5)

My initial idea would be to fix `_target_is_valid` in tower.gd by adding:
`attack_range = Utils.apply_unit_range_extension(attack_range, _attack_target_type)`

**Comment by Kvel2D** [comment]
From these notes, I mainly see that `Tower._update_target_list()` has a bug about `RANGE_CHECK_BONUS_FOR_OTHER_UNITS`.

1. It calls `Utils.get_units_in_range()` which adds `RANGE_CHECK_BONUS_FOR_OTHER_UNITS`
2. It also calls `_target_is_valid()` which does NOT add `RANGE_CHECK_BONUS_FOR_OTHER_UNITS`

I can confirm, current behavior is incorrect.

This fix is fine:
> My initial idea would be to fix _target_is_valid in tower.gd by adding:
attack_range = Utils.apply_unit_range_extension(attack_range, _attack_target_type)
