### ISSUE TITLE
Design UI layout

### ISSUE THREAD

**Issue by Kvel2D** [Praytic/youtd2#56]

**Comment by Praytic** [comment]
![image](https://user-images.githubusercontent.com/10060411/236707308-c9c4aba9-4d56-4b75-bc17-58007492b677.png)
> 1. What's the location of the buttons for selling and upgrading currently selected tower?
> 2. What's the location of the tooltip of currently selected tower. Not the "tooltip" which displays 100 stats, but the same tooltip that's shown for tower build buttons.
> 3. What's the location of the tooltip (same as 2) for upgraded version of the currently selected tower. Shown when hovering over upgrade tower button.
> 4. What's the location of buffs of selected unit (both for towers and creeps)?
> 5. What's the location of the tower inventory?
> 6. Showing the tooltip for tower build buttons at different places is bad design in my opinion. Eyes have to jump from one spot to another. If tooltip stays in same place, eyes can stay in same place while mouse moves over towers.
All other logic which needs to be displayed should go to the right show-on-action panel.
