### ISSUE TITLE
Web export on MacOS takes long time to load in any browser

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#60]
Track this issue here:
https://github.com/godotengine/godot/issues/70691

**Comment by Praytic** [comment]
Should be fixed when this PR is merged and released. https://github.com/godotengine/godot/pull/85939

**Comment by Kvel2D** [comment]
Moved to Backlog https://github.com/Praytic/youtd2/discussions/407

**Comment by Kvel2D** [comment]
Project was migrated to Godot 4.3 which includes a fix for issues on web build on mac.
