### ISSUE TITLE
Sending multiple waves rapidly causes NPE

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#76]
**Issue:**
<img width="715" alt="Screenshot 2023-05-04 at 6 10 08 PM" src="https://user-images.githubusercontent.com/10060411/236359828-27823667-0ab1-4e39-aa81-5b4c66b75022.png">
Although we have a null check in the code, the spawn_creep(creep) function appears to have a null argument.

**How to reproduce:**
Send 3 waves one by one. Build a couple of towers after that. Let some creeps reach the portal.

**Comment by Kvel2D** [comment]
This is not NPE, but using an object reference after it has been free'd.
