### ISSUE TITLE
Add foggy filter to lessen color pop, especially around edges of the viewport

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#78]
Currently:
![image](https://user-images.githubusercontent.com/10060411/236601778-4a2b0922-a439-45db-b353-97160b930479.png)

Desired result:
![image](https://user-images.githubusercontent.com/10060411/236601764-ef9eca43-2ae4-45b9-869b-cddb725b2ede.png)

**Comment by Kvel2D** [comment]
https://godotshaders.com/shader/vignette-shader-for-godot-4/
