### ISSUE TITLE
Optimize workflow for building and publishing the game

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#85]
Currently it takes too long (>15m) for it to download assets and move them around the jobs. Plus, we're doing double export for the game due to this bug: https://github.com/godotengine/godot/issues/75684

**Comment by Kvel2D** [comment]
Appears to be fixed? Workflow completes in a reasonable amount of time. Mac workflow is broken and will be broken for the foreseeable future.

**Comment by Kvel2D** [comment]
WONTDO
Good enough.
