### ISSUE TITLE
Create mockups and update export sheet for 'Tower Info' panel

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#95]
The 'Tower Info' panel should contain all information related to the Tower class, as well as other clickable elements that lead to tower-related information.
Here's a rough visualization of the tower's stats:
![tower stats](https://github.com/Praytic/youtd2/assets/10060411/f0082012-e885-4d72-880c-01af3cab0790)
...and tower description window with extra space for skills, wearable items, etc.:
![tower description](https://cdn.discordapp.com/attachments/1116928594850107483/1117043081494155274/image.png)

**Thanks to [jhoijhoi](https://github.com/jhoijhoi) for visual prototypes.**

**Comment by jhoijhoi** [comment]
![image](https://github.com/Praytic/youtd2/assets/136144092/ba45c1f8-ef3b-457c-ba33-ecfda97d3681)
Updated as Praytic wanted the panel to float on the right. 
Top 3 are Level, Upgrade, Sell
Top left are Tower Info and Tower Stats
Left bottom 6 are item slots (would only show how many actual slots the tower had)
Bottom 4 are the specials (castable or not), again only showing if the tower has them
For towers that are super simple (no specials, 1 item slot), the height of the box would obviously just shrink to fit what was needed
I think the scale of the buttons is about right, slightly bigger than the element buttons, but smaller than the build hud buttons
