### ISSUE TITLE
Create mockups and update export sheet for the 'Current Wave' bar

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#97]
![](https://cdn.discordapp.com/attachments/1116928594850107483/1117036480875995176/image.png)

**Thanks to [jhoijhoi](https://github.com/jhoijhoi) for visual prototypes.**

**Comment by Kvel2D** [comment]
Moved to Backlog https://github.com/Praytic/youtd2/discussions/407

**Comment by Kvel2D** [comment]
Closing this because won't be making current wave bar.
