### ISSUE TITLE
Make buildable area more obvious for players

### ISSUE THREAD

**Issue by Praytic** [Praytic/youtd2#98]
![](https://cdn.discordapp.com/attachments/1116928594850107483/1116950432791658667/image.png)

**Comment by Leiyiliro** [comment]
To add to this, maybe having a tile grid would help that becomes visible when you are preparing to build a tower. Also, allowing for building "half-tile" between rows, as in the original version that made the auras cover more tiles.

**Comment by Kvel2D** [comment]
> To add to this, maybe having a tile grid would help that becomes visible when you are preparing to build a tower. Also, allowing for building "half-tile" between rows, as in the original version that made the auras cover more tiles. One other thing would be to show another circle for the aura range, besides the attack range of the tower.

I created a separate issue about aura ranges: https://github.com/Praytic/youtd2/issues/269
Regarding half tiles - we are currently not sure if we want to add this feature so can't add this to backlog yet.
